// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: v1/sysmon_api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на получение статистики
type GetStatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// период отдачи статистики, сек (каждые N)
	Period int32 `protobuf:"varint,1,opt,name=period,proto3" json:"period,omitempty"`
	// диапазон усреднения, сек (за последние M)
	Average int32 `protobuf:"varint,2,opt,name=average,proto3" json:"average,omitempty"`
}

func (x *GetStatRequest) Reset() {
	*x = GetStatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_sysmon_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatRequest) ProtoMessage() {}

func (x *GetStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sysmon_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatRequest.ProtoReflect.Descriptor instead.
func (*GetStatRequest) Descriptor() ([]byte, []int) {
	return file_v1_sysmon_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatRequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *GetStatRequest) GetAverage() int32 {
	if x != nil {
		return x.Average
	}
	return 0
}

// Поток статистики
type GetStatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// данные
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetStatResponse) Reset() {
	*x = GetStatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_sysmon_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatResponse) ProtoMessage() {}

func (x *GetStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_sysmon_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatResponse.ProtoReflect.Descriptor instead.
func (*GetStatResponse) Descriptor() ([]byte, []int) {
	return file_v1_sysmon_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_v1_sysmon_api_proto protoreflect.FileDescriptor

var file_v1_sysmon_api_proto_rawDesc = []byte{
	0x0a, 0x13, 0x76, 0x31, 0x2f, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31,
	0x22, 0x42, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x76,
	0x65, 0x72, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x76, 0x65,
	0x72, 0x61, 0x67, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x4f, 0x0a, 0x09, 0x53,
	0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x41, 0x50, 0x49, 0x12, 0x42, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x12, 0x19, 0x2e, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09,
	0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_v1_sysmon_api_proto_rawDescOnce sync.Once
	file_v1_sysmon_api_proto_rawDescData = file_v1_sysmon_api_proto_rawDesc
)

func file_v1_sysmon_api_proto_rawDescGZIP() []byte {
	file_v1_sysmon_api_proto_rawDescOnce.Do(func() {
		file_v1_sysmon_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_sysmon_api_proto_rawDescData)
	})
	return file_v1_sysmon_api_proto_rawDescData
}

var file_v1_sysmon_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_sysmon_api_proto_goTypes = []interface{}{
	(*GetStatRequest)(nil),  // 0: sysmon.v1.GetStatRequest
	(*GetStatResponse)(nil), // 1: sysmon.v1.GetStatResponse
}
var file_v1_sysmon_api_proto_depIdxs = []int32{
	0, // 0: sysmon.v1.SysmonAPI.GetStat:input_type -> sysmon.v1.GetStatRequest
	1, // 1: sysmon.v1.SysmonAPI.GetStat:output_type -> sysmon.v1.GetStatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_sysmon_api_proto_init() }
func file_v1_sysmon_api_proto_init() {
	if File_v1_sysmon_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_sysmon_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_sysmon_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_sysmon_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_sysmon_api_proto_goTypes,
		DependencyIndexes: file_v1_sysmon_api_proto_depIdxs,
		MessageInfos:      file_v1_sysmon_api_proto_msgTypes,
	}.Build()
	File_v1_sysmon_api_proto = out.File
	file_v1_sysmon_api_proto_rawDesc = nil
	file_v1_sysmon_api_proto_goTypes = nil
	file_v1_sysmon_api_proto_depIdxs = nil
}
