# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: sysmon-check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Check out code
      uses: actions/checkout@v3

    - name: Linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.60.1
        working-directory: ${{ env.BRANCH }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Check out
        uses: actions/checkout@v3

      - name: Unit test
        run: go test -v -count=1 -race -count 2 -timeout=1m ./...
        working-directory: ${{ env.BRANCH }}


  tests_by_makefile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint
        working-directory: ${{ env.BRANCH }}

      - name: make build
        run: make build
        working-directory: ${{ env.BRANCH }}

      - name: make test
        run: make test
        working-directory: ${{ env.BRANCH }}

